
-- Add opening_stock and purchased_stock to inventory_items
ALTER TABLE public.inventory_items 
ADD COLUMN IF NOT EXISTS opening_stock integer DEFAULT 0;

ALTER TABLE public.inventory_items 
ADD COLUMN IF NOT EXISTS purchased_stock integer DEFAULT 0;

-- Create inventory_purchases table
CREATE TABLE IF NOT EXISTS public.inventory_purchases (
    id bigint generated by default as identity primary key,
    inventory_id bigint references public.inventory_items(id) on delete cascade,
    quantity integer not null,
    purchase_date date not null default current_date,
    created_at timestamp with time zone default now()
);

-- Refresh schema
NOTIFY pgrst, 'reload schema';
