
-- ==========================================
-- FINAL INVENTORY & COSTING MIGRATION
-- ==========================================

-- 1. Ensure inventory_items has all required columns
ALTER TABLE public.inventory_items 
ADD COLUMN IF NOT EXISTS code text,
ADD COLUMN IF NOT EXISTS description text,
ADD COLUMN IF NOT EXISTS unit text,
ADD COLUMN IF NOT EXISTS price numeric(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS stock integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS opening_stock integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS purchased_stock integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS critical_stock integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_outsource boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS vendor_name text,
ADD COLUMN IF NOT EXISTS outsource_type text,
ADD COLUMN IF NOT EXISTS truck_schedule text,
ADD COLUMN IF NOT EXISTS location text;

-- 2. Create inventory_purchases table
CREATE TABLE IF NOT EXISTS public.inventory_purchases (
    id bigint generated by default as identity primary key,
    inventory_id bigint references public.inventory_items(id) on delete cascade,
    quantity integer not null,
    purchase_date date not null default current_date,
    created_at timestamp with time zone default now()
);

-- 3. Create inventory_consumption table
CREATE TABLE IF NOT EXISTS public.inventory_consumption (
    id uuid default gen_random_uuid() primary key,
    inventory_id bigint references public.inventory_items(id) on delete cascade,
    job_id text not null, -- References the job ID string
    quantity integer not null,
    consumption_date date not null default current_date,
    created_at timestamp with time zone default now()
);

-- 4. Create inventory_price_history table
CREATE TABLE IF NOT EXISTS public.inventory_price_history (
    id uuid default gen_random_uuid() primary key,
    inventory_id bigint references public.inventory_items(id) on delete cascade,
    price numeric(10,2) not null,
    effective_date date not null default current_date,
    created_at timestamp with time zone default now()
);

-- 5. Create job_cost_sheets table
CREATE TABLE IF NOT EXISTS public.job_cost_sheets (
    job_id text primary key, -- One sheet per job
    items jsonb not null default '[]'::jsonb, -- Array of CostSheetItem
    status text not null default 'Issued', -- 'Issued', 'Returned', 'Finalized'
    total_cost numeric(12,2) default 0,
    packing_date date,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- 6. Enable RLS (Optional but recommended)
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_consumption ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_price_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_cost_sheets ENABLE ROW LEVEL SECURITY;

-- 7. Basic RLS Policies (Allow all for authenticated users for now)
-- You can harden these later based on roles
CREATE POLICY "Allow all for authenticated users" ON public.inventory_items FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all for authenticated users" ON public.inventory_purchases FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all for authenticated users" ON public.inventory_consumption FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all for authenticated users" ON public.inventory_price_history FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all for authenticated users" ON public.job_cost_sheets FOR ALL TO authenticated USING (true);

-- 8. Refresh schema
NOTIFY pgrst, 'reload schema';
